# pyenv (sets up path and autocompletion)
status --is-interactive; and source (pyenv init -|psub)
# if the above yields a sourcing error, try the following
# status --is-interactive; and pyenv init - | source

# This one was autogenerated by the fish script, I donno what it does
# status --is-interactive; and . (pyenv init -|psub)

# Gemfury
set -gx GEMFURY_TOKEN zpMTeWRMyz7zBeywfWDs #get from Local Env Secrets in 1Password Tech vault>

# pipenv
set -gx PIPENV_DEFAULT_PYTHON_VERSION 3.6
set PATH $PATH ~/.local/bin

# Base dir for your repos - modify to the correct path
set -gx PROJECT_DIR /Users/katebrender/Development/Boost

# virtualenv (optional)
set -gx VIRTUAL_ENV_DISABLE_PROMPT 1

# Hide fish greeting (optional)
function fish_greeting
end

alias dc="docker-compose -f $PROJECT_DIR/local-dev/docker-compose.yml \
 	-f $PROJECT_DIR/local-dev/docker-compose.override.yml"

alias boost="cd ~/Development/Boost"
alias desktop="cd ~/Desktop"
alias development="cd ~/Development"
alias notes="cd ~/Desktop/notes"

alias autobots="cd /Users/katebrender/Development/Boost/autobots"
alias barker="cd /Users/katebrender/Development/Boost/barker"
alias boost-utils="cd /Users/katebrender/Development/Boost/boost-utils"
alias cookiecutter="cd /Users/katebrender/Development/Boost/cookiecutter-boost-service"
alias devops="cd /Users/katebrender/Development/Boost/devops"
alias dewey="cd /Users/katebrender/Development/Boost/dewey"
alias edwin="cd /Users/katebrender/Development/Boost/edwin"
alias eiger="cd /Users/katebrender/Development/Boost/eiger"
alias ella="cd /Users/katebrender/Development/Boost/ella"
alias everett="cd /Users/katebrender/Development/Boost/everett"
alias franklin="cd /Users/katebrender/Development/Boost/franklin"
alias gutenberg="cd /Users/katebrender/Development/Boost/gutenberg"
alias hancock="cd /Users/katebrender/Development/Boost/hancock"
alias hancock="cd /Users/katebrender/Development/Boost/hancock"
alias jeeves="cd /Users/katebrender/Development/Boost/jeeves"
alias kestrel="cd /Users/katebrender/Development/Boost/kestrel"
alias local-dev="cd /Users/katebrender/Development/Boost/local-dev"
alias ofac="cd /Users/katebrender/Development/Boost/ofac"
alias quoting="cd /Users/katebrender/Development/Boost/quoting"
alias serverless="cd /Users/katebrender/Development/Boost/serverless"
alias steve="cd /Users/katebrender/Development/Boost/steve"

function fish_prompt
	set_color blue
	date +%H:%M
	set_color green
	echo (pwd)
	set_color blue
	echo The Prompt ☆ (set_color normal)
end
